"""
End-to-end test client for the APIMarket escrow-upgrades patch.

Tests:

  1. Escrow health endpoint.
  2. Escrow analytics endpoint.
  3. Create a temporary upstream API that returns HTTP 206.
  4. Create a marketplace listing pointing to that upstream.
  5. Register an agent.
  6. Request the listing without payment -> expect 402.
  7. Pay the quote on Algorand Testnet.
  8. Retry with payment proof.
  9. Upstream returns HTTP 206 + X-Partial-Share-Bps: 7000.
 10. Verify PARTIALLY_COMPLETED transaction.
 11. Verify PARTIALLY_RELEASED escrow.
 12. Verify provider/agent split amounts.
 13. Verify partial_transactions increased.
 14. Check escrow health and analytics after settlement.
 15. Verify new dispute/evidence validation behavior.

The patch introduces:

    HTTP 206
        -> PARTIALLY_COMPLETED

    X-Partial-Share-Bps: 7000
        -> provider gets 70%
        -> agent gets 30%

Usage:

    export PAYER_MNEMONIC="your funded testnet mnemonic"

    python scripts/test_patch.py \
        --base-url http://localhost:8000
"""

import argparse
import json
import os
import sys
import threading
import time
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

import httpx

from algosdk import account, mnemonic
from algosdk.transaction import (
    AssetTransferTxn,
    PaymentTxn,
    wait_for_confirmation,
)
from algosdk.v2client import algod


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

ALGOD_ADDRESS = "https://testnet-api.algonode.cloud"

# Must match your server's USDC_TESTNET_ASA_ID.
DEMO_ASA_ID = 10458941

# Temporary local upstream.
MOCK_HOST = "127.0.0.1"
MOCK_PORT = 8765

# Provider receives 70%.
# 7000 basis points = 70%.
PARTIAL_SHARE_BPS = 7000

# Price used by the test listing.
TEST_PRICE = 100000


# ---------------------------------------------------------------------------
# Mock upstream API
# ---------------------------------------------------------------------------

class PartialAPIHandler(BaseHTTPRequestHandler):
    """
    Fake provider API.

    The APIMarket proxy calls this endpoint.

    It returns:

        HTTP 206
        X-Partial-Share-Bps: 7000

    Therefore the patch should perform:

        Provider = 70%
        Agent    = 30%
    """

    def do_GET(self):
        body = json.dumps(
            {
                "status": "partial",
                "message": "Partial response generated by patch test",
                "items_returned": 7,
                "items_expected": 10,
            }
        ).encode()

        self.send_response(206)

        self.send_header(
            "Content-Type",
            "application/json",
        )

        self.send_header(
            "X-Partial-Share-Bps",
            str(PARTIAL_SHARE_BPS),
        )

        self.send_header(
            "Content-Length",
            str(len(body)),
        )

        self.end_headers()

        self.wfile.write(body)

    def log_message(self, format, *args):
        # Don't print HTTP server logs.
        return


def start_mock_upstream():
    server = ThreadingHTTPServer(
        (MOCK_HOST, MOCK_PORT),
        PartialAPIHandler,
    )

    thread = threading.Thread(
        target=server.serve_forever,
        daemon=True,
    )

    thread.start()

    return server


# ---------------------------------------------------------------------------
# Algorand payment
# ---------------------------------------------------------------------------

def pay_quote(quote_body: dict, payer_mnemonic: str) -> str:
    """
    Pay the exact x402 quote.

    Supports:

        asa:<id> -> USDC ASA
        otherwise -> native ALGO
    """

    private_key = mnemonic.to_private_key(
        payer_mnemonic
    )

    payer_address = account.address_from_private_key(
        private_key
    )

    algod_client = algod.AlgodClient(
        "",
        ALGOD_ADDRESS,
    )

    params = algod_client.suggested_params()

    pay_to = quote_body["payTo"]

    amount = int(
        quote_body["maxAmountRequired"]
    )

    asset_label = quote_body["asset"]

    print()
    print("   Payment details:")
    print(f"     payer:  {payer_address}")
    print(f"     payTo:  {pay_to}")
    print(f"     amount: {amount}")
    print(f"     asset:  {asset_label}")

    if asset_label.startswith("asa:"):
        asa_id = int(
            asset_label.split(":", 1)[1]
        )

        txn = AssetTransferTxn(
            sender=payer_address,
            sp=params,
            receiver=pay_to,
            amt=amount,
            index=asa_id,
        )

    else:
        txn = PaymentTxn(
            sender=payer_address,
            sp=params,
            receiver=pay_to,
            amt=amount,
        )

    signed = txn.sign(private_key)

    tx_id = algod_client.send_transaction(
        signed
    )

    print(f"   submitted payment: {tx_id}")

    wait_for_confirmation(
        algod_client,
        tx_id,
        10,
    )

    print("   payment confirmed")

    return tx_id


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def fail(message: str):
    print()
    print(f"❌ TEST FAILED: {message}")
    sys.exit(1)


def check(condition: bool, message: str):
    if not condition:
        fail(message)

    print(f"   ✓ {message}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--base-url",
        default="http://localhost:8000",
    )

    parser.add_argument(
        "--payer-mnemonic",
        default=None,
        help="Overrides $PAYER_MNEMONIC",
    )

    args = parser.parse_args()

    payer_mnemonic = (
        args.payer_mnemonic
        or os.environ.get("PAYER_MNEMONIC")
    )

    if not payer_mnemonic:
        print(
            "Set PAYER_MNEMONIC or pass "
            "--payer-mnemonic"
        )
        sys.exit(1)

    # Validate mnemonic before doing anything.
    private_key = mnemonic.to_private_key(
        payer_mnemonic
    )

    payer_address = account.address_from_private_key(
        private_key
    )

    client = httpx.Client(
        base_url=args.base_url,
        timeout=70.0,
    )

    # -----------------------------------------------------------------------
    # Start mock upstream
    # -----------------------------------------------------------------------

    print()
    print("=" * 70)
    print("APIMarket PATCH TEST")
    print("=" * 70)

    print()
    print("0. Starting temporary partial-response API...")

    mock_server = start_mock_upstream()

    upstream_url = (
        f"http://{MOCK_HOST}:{MOCK_PORT}/partial"
    )

    print(
        f"   upstream: {upstream_url}"
    )

    # Give the local server a moment to start.
    time.sleep(0.2)

    # -----------------------------------------------------------------------
    # 1. Escrow health
    # -----------------------------------------------------------------------

    print()
    print("1. Testing GET /api/escrow/health...")

    health_resp = client.get(
        "/api/escrow/health"
    )

    check(
        health_resp.status_code == 200,
        f"health endpoint returned {health_resp.status_code}",
    )

    health = health_resp.json()

    print(
        f"   held:      {health['outstanding_held_microalgos']}"
    )

    print(
        f"   held count:{health['outstanding_held_count']}"
    )

    print(
        f"   disputed:  {health['disputed_microalgos']}"
    )

    print(
        f"   liability: {health['total_platform_liability_microalgos']}"
    )

    # -----------------------------------------------------------------------
    # 2. Escrow analytics
    # -----------------------------------------------------------------------

    print()
    print(
        "2. Testing GET /api/escrow/analytics/by-listing..."
    )

    analytics_resp = client.get(
        "/api/escrow/analytics/by-listing"
    )

    check(
        analytics_resp.status_code == 200,
        f"analytics endpoint returned {analytics_resp.status_code}",
    )

    analytics = analytics_resp.json()

    print(
        f"   listings with escrow history: {len(analytics)}"
    )

    # -----------------------------------------------------------------------
    # 3. Create test listing
    # -----------------------------------------------------------------------

    test_path = (
        "patch-partial-test-"
        + uuid.uuid4().hex[:8]
    )

    print()
    print(
        "3. Creating test listing..."
    )

    listing_resp = client.post(
        "/api/listings",
        json={
            "name": "Patch Partial Test API",
            "description": (
                "Temporary API used to test "
                "partial escrow settlement"
            ),
            "category": "testing",
            "path": test_path,
            "upstream_url": upstream_url,
            "price_microalgos": TEST_PRICE,
            "pay_to_address": payer_address,
            "asa_id": DEMO_ASA_ID,
        },
    )

    check(
        listing_resp.status_code in (200, 201),
        f"listing creation returned {listing_resp.status_code}",
    )

    listing = listing_resp.json()

    listing_id = listing["id"]

    print(
        f"   listing id: {listing_id}"
    )

    print(
        f"   path: {test_path}"
    )

    # -----------------------------------------------------------------------
    # 4. Register agent
    # -----------------------------------------------------------------------

    print()
    print(
        "4. Registering test agent..."
    )

    agent_resp = client.post(
        "/api/agents",
        json={
            "name": (
                "Patch Test Agent "
                + uuid.uuid4().hex[:8]
            ),
            "wallet_address": payer_address,
            "policy": {
                "max_transaction_amount": "5.00",
                "daily_limit": "50.00",
                "min_provider_reputation": 0,
            },
        },
    )

    check(
        agent_resp.status_code == 201,
        f"agent creation returned {agent_resp.status_code}",
    )

    agent = agent_resp.json()

    api_key = agent["api_key"]

    print(
        f"   agent: {agent['id']}"
    )

    # -----------------------------------------------------------------------
    # 5. Get quote
    # -----------------------------------------------------------------------

    print()
    print(
        "5. Requesting test API without payment..."
    )

    first = client.get(
        f"/market/{test_path}/call",
        headers={
            "X-Agent-Key": api_key
        },
    )

    check(
        first.status_code == 402,
        f"received expected 402 (got {first.status_code})",
    )

    quote_body = first.json()

    print(
        f"   escrow wallet: {quote_body['payTo']}"
    )

    print(
        f"   amount: {quote_body['maxAmountRequired']}"
    )

    print(
        f"   asset: {quote_body['asset']}"
    )

    # -----------------------------------------------------------------------
    # 6. Pay quote
    # -----------------------------------------------------------------------

    print()
    print(
        "6. Paying quote on Algorand Testnet..."
    )

    tx_id = pay_quote(
        quote_body,
        payer_mnemonic,
    )

    # -----------------------------------------------------------------------
    # 7. Retry with proof
    # -----------------------------------------------------------------------

    print()
    print(
        "7. Retrying request with payment proof..."
    )

    proof = json.dumps(
        {
            "tx_id": tx_id,
            "quote": quote_body["quote"],
        }
    )

    # Give the indexer/Algorand verification a moment.
    time.sleep(2)

    second = client.get(
        f"/market/{test_path}/call",
        headers={
            "X-Agent-Key": api_key,
            "X-402-Payment-Proof": proof,
        },
    )

    print(
        f"   HTTP status: {second.status_code}"
    )

    print(
        f"   response: {second.text[:500]}"
    )

    check(
        second.status_code == 206,
        "upstream HTTP 206 reached the client",
    )

    # -----------------------------------------------------------------------
    # 8. Find transaction
    # -----------------------------------------------------------------------

    print()
    print(
        "8. Checking transaction..."
    )

    txn_id = second.headers.get(
        "X-Transaction-Id"
    )

    check(
        txn_id is not None,
        "X-Transaction-Id header exists",
    )

    txn_resp = client.get(
        f"/api/transactions/{txn_id}"
    )

    check(
        txn_resp.status_code == 200,
        "transaction endpoint returned 200",
    )

    txn = txn_resp.json()

    print(
        f"   transaction id: {txn_id}"
    )

    print(
        f"   transaction status: {txn['status']}"
    )

    check(
        txn["status"] == "PARTIALLY_COMPLETED",
        "transaction status is PARTIALLY_COMPLETED",
    )

    # -----------------------------------------------------------------------
    # 9. Find escrow
    # -----------------------------------------------------------------------

    print()
    print(
        "9. Checking partial escrow settlement..."
    )

    escrows_resp = client.get(
        "/api/escrow"
    )

    check(
        escrows_resp.status_code == 200,
        "escrow endpoint returned 200",
    )

    escrows = escrows_resp.json()

    escrow = next(
        (
            e
            for e in escrows
            if str(e["transaction_id"])
            == str(txn_id)
        ),
        None,
    )

    check(
        escrow is not None,
        "escrow row found for transaction",
    )

    print(
        f"   escrow status: {escrow['status']}"
    )

    check(
        escrow["status"]
        == "PARTIALLY_RELEASED",
        "escrow status is PARTIALLY_RELEASED",
    )

    # -----------------------------------------------------------------------
    # 10. Verify split
    # -----------------------------------------------------------------------

    print()
    print(
        "10. Verifying provider/agent split..."
    )

    provider_share = escrow[
        "provider_share_bps"
    ]

    provider_amount = escrow[
        "provider_amount_microalgos"
    ]

    agent_amount = escrow[
        "agent_amount_microalgos"
    ]

    print(
        f"   provider share: {provider_share} bps"
    )

    print(
        f"   provider amount: {provider_amount}"
    )

    print(
        f"   agent refund: {agent_amount}"
    )

    check(
        provider_share == PARTIAL_SHARE_BPS,
        "provider share is 7000 bps (70%)",
    )

    # The patch calculates:
    #
    # provider_amount =
    #     total * provider_share_bps / 10000
    #
    # agent_amount =
    #     total - provider_amount
    #
    expected_provider = (
        TEST_PRICE
        * PARTIAL_SHARE_BPS
        // 10_000
    )

    expected_agent = (
        TEST_PRICE
        - expected_provider
    )

    check(
        provider_amount == expected_provider,
        f"provider amount is {expected_provider}",
    )

    check(
        agent_amount == expected_agent,
        f"agent refund is {expected_agent}",
    )

    check(
        provider_amount + agent_amount
        == TEST_PRICE,
        "provider + agent amounts equal original escrow",
    )

    # -----------------------------------------------------------------------
    # 11. Check on-chain transactions
    # -----------------------------------------------------------------------

    print()
    print(
        "11. Checking payout/refund transaction IDs..."
    )

    print(
        f"   provider payout tx: "
        f"{escrow.get('payout_tx_id')}"
    )

    print(
        f"   agent refund tx: "
        f"{escrow.get('refund_tx_id')}"
    )

    check(
        escrow.get("payout_tx_id") is not None,
        "provider payout transaction exists",
    )

    check(
        escrow.get("refund_tx_id") is not None,
        "agent refund transaction exists",
    )

    # -----------------------------------------------------------------------
    # 12. Check partial reputation counter
    # -----------------------------------------------------------------------

    print()
    print(
        "12. Checking partial transaction tracking..."
    )

    listing_after = client.get(
        f"/api/listings/{listing_id}"
    )

    if listing_after.status_code == 200:

        listing_data = listing_after.json()

        print(
            f"   partial_transactions: "
            f"{listing_data.get('partial_transactions')}"
        )

        if "partial_transactions" in listing_data:
            check(
                listing_data["partial_transactions"] >= 1,
                "partial transaction was recorded",
            )
        else:
            print(
                "   NOTE: listing response does not expose "
                "partial_transactions"
            )

    else:

        print(
            f"   NOTE: listing GET returned "
            f"{listing_after.status_code}; skipping counter check"
        )

    # -----------------------------------------------------------------------
    # 13. Test evidence validation
    # -----------------------------------------------------------------------

    print()
    print(
        "13. Testing evidence endpoint validation..."
    )

    # A PARTIALLY_RELEASED escrow is no longer DISPUTED,
    # so /evidence should reject it with 409.

    evidence_resp = client.post(
        f"/api/escrow/{escrow['id']}/evidence",
        json={
            "submitted_by": "agent",
            "message": "This should be rejected because the escrow is already settled.",
        },
    )

    print(
        f"   evidence response: "
        f"{evidence_resp.status_code}"
    )

    check(
        evidence_resp.status_code == 409,
        "evidence endpoint correctly rejects non-DISPUTED escrow",
    )

    # -----------------------------------------------------------------------
    # 14. Test partial-release validation
    # -----------------------------------------------------------------------

    print()
    print(
        "14. Testing partial-release validation..."
    )

    partial_resp = client.post(
        f"/api/escrow/{escrow['id']}/partial-release",
        json={
            "provider_share_bps": 5000,
            "notes": "Should not be accepted after settlement.",
        },
    )

    print(
        f"   partial-release response: "
        f"{partial_resp.status_code}"
    )

    check(
        partial_resp.status_code == 409,
        "partial-release correctly rejects already-settled escrow",
    )

    # -----------------------------------------------------------------------
    # 15. Final escrow health
    # -----------------------------------------------------------------------

    print()
    print(
        "15. Checking final escrow health..."
    )

    final_health_resp = client.get(
        "/api/escrow/health"
    )

    check(
        final_health_resp.status_code == 200,
        "final health endpoint returned 200",
    )

    final_health = final_health_resp.json()

    print(
        f"   held: {final_health['outstanding_held_microalgos']}"
    )

    print(
        f"   disputed: {final_health['disputed_microalgos']}"
    )

    print(
        f"   total liability: "
        f"{final_health['total_platform_liability_microalgos']}"
    )

    # -----------------------------------------------------------------------
    # 16. Final analytics
    # -----------------------------------------------------------------------

    print()
    print(
        "16. Checking final listing analytics..."
    )

    final_analytics_resp = client.get(
        "/api/escrow/analytics/by-listing"
    )

    check(
        final_analytics_resp.status_code == 200,
        "analytics endpoint returned 200",
    )

    final_analytics = final_analytics_resp.json()

    matching = [
        item
        for item in final_analytics
        if str(item["listing_id"])
        == str(listing_id)
    ]

    if matching:

        item = matching[0]

        print(
            f"   listing: {item['listing_name']}"
        )

        print(
            f"   total escrows: {item['total_escrows']}"
        )

        print(
            f"   released: {item['released']}"
        )

        print(
            f"   partially released: "
            f"{item['partially_released']}"
        )

        print(
            f"   refunded: {item['refunded']}"
        )

        print(
            f"   disputed: {item['disputed']}"
        )

        print(
            f"   dispute rate: {item['dispute_rate']}"
        )

        print(
            f"   refund rate: {item['refund_rate']}"
        )

        print(
            f"   avg resolution: "
            f"{item['avg_resolution_seconds']}"
        )

        check(
            item["partially_released"] >= 1,
            "analytics records the partial release",
        )

    # -----------------------------------------------------------------------
    # Cleanup
    # -----------------------------------------------------------------------

    print()
    print(
        "17. Stopping temporary upstream..."
    )

    mock_server.shutdown()

    client.close()

    print()
    print("=" * 70)
    print("✅ PATCH TEST COMPLETED SUCCESSFULLY")
    print("=" * 70)


if __name__ == "__main__":
    main()